export type CurrencyCode =
  | 'CNY'
  | 'USD'
  | 'EUR'
  | 'GBP'
  | 'JPY'
  | 'KRW'
  | 'HKD'
  | 'TWD'
  | 'SGD'
  | 'AUD'
  | 'CAD'
  | 'CHF'
  | 'SEK'
  | 'NOK'
  | 'DKK'
  | 'INR'
  | 'THB'
  | 'MYR'
  | 'IDR'
  | 'PHP'
  | 'VND'
  | 'MXN'
  | 'BRL'
  | 'RUB'
  | 'ZAR';

export type CartItemId = string;
export type ProductId = string;
export type VariantId = string;
export type CouponCode = string;
export type ISODateTimeString = string;

/**
 * Represents monetary values stored as "minor units" (e.g. cents),
 * to avoid floating point precision issues.
 */
export interface IMoney {
  /**
   * Currency code in ISO 4217 format (e.g. "CNY", "USD").
   */
  currency: CurrencyCode;
  /**
   * Monetary value expressed in minor units.
   * Example: $10.99 => amountMinor = 1099.
   */
  amountMinor: number;
}

/**
 * A lightweight reference for a product, designed for safe reuse across
 * stores/features without pulling in the full product domain model.
 */
export interface IProductRef {
  /**
   * Unique product identifier.
   */
  productId: ProductId;

  /**
   * Optional variant identifier if the product has variants.
   */
  variantId?: VariantId;

  /**
   * Display name captured at the time of add-to-cart.
   */
  name: string;

  /**
   * Optional SKU for inventory/tracking.
   */
  sku?: string;

  /**
   * Optional brand name.
   */
  brand?: string;

  /**
   * Optional primary image url for UI rendering.
   */
  imageUrl?: string;

  /**
   * Optional product page url for navigation.
   */
  productUrl?: string;
}

/**
 * A single item in the cart. Use `id` as stable key for UI lists and
 * `productRef` for product/variant identification.
 */
export interface ICartItem {
  /**
   * Stable cart item id (generated by client or backend).
   */
  id: CartItemId;

  /**
   * The referenced product/variant.
   */
  productRef: IProductRef;

  /**
   * Quantity of this item in cart.
   */
  quantity: number;

  /**
   * Unit price snapshot at the time of add-to-cart or last refresh.
   */
  unitPrice: IMoney;

  /**
   * Total price for this line = unitPrice * quantity - line discounts (if any).
   * If your domain does not maintain it, it can be derived.
   */
  lineTotal?: IMoney;

  /**
   * Whether this item is currently available/valid (e.g. in stock).
   */
  available?: boolean;

  /**
   * Optional reason if item is unavailable/invalid.
   */
  unavailableReason?: string;

  /**
   * Optional per-item attributes (e.g. size/color) for display and identification.
   */
  attributes?: Readonly<Record<string, string>>;

  /**
   * Optional user note attached to the item (e.g. gift message).
   */
  note?: string;

  /**
   * Optional metadata for integrations or experiments.
   */
  metadata?: Readonly<Record<string, string>>;

  /**
   * Timestamp when the item was added to cart.
   */
  addedAt?: ISODateTimeString;

  /**
   * Timestamp when the item was last updated.
   */
  updatedAt?: ISODateTimeString;
}

/**
 * Coupon/discount information applied to the cart.
 */
export interface ICartDiscount {
  /**
   * Coupon or promotion code.
   */
  code: CouponCode;

  /**
   * Human-readable description.
   */
  description?: string;

  /**
   * Discount amount applied (positive amountMinor representing reduction).
   */
  amount: IMoney;

  /**
   * Whether the discount is currently valid.
   */
  valid?: boolean;

  /**
   * If invalid, provide reason for UI.
   */
  invalidReason?: string;
}

/**
 * Shipping method selection summary.
 */
export interface ICartShipping {
  /**
   * Shipping method identifier.
   */
  methodId: string;

  /**
   * Display name for the shipping method.
   */
  methodName: string;

  /**
   * Shipping fee.
   */
  fee: IMoney;

  /**
   * Estimated delivery text for UI.
   */
  etaText?: string;
}

/**
 * Tax summary for the cart.
 */
export interface ICartTax {
  /**
   * Tax amount.
   */
  amount: IMoney;

  /**
   * Optional tax rate (0..1), if applicable.
   */
  rate?: number;

  /**
   * Optional display label (e.g. "VAT", "Sales Tax").
   */
  label?: string;
}

/**
 * A computed summary of cart totals; designed to be stored and reused
 * as a single object by stores and UI layers.
 */
export interface ICartSummary {
  /**
   * Total quantity across all cart items.
   */
  itemCount: number;

  /**
   * Subtotal before discounts/taxes/shipping.
   */
  subtotal: IMoney;

  /**
   * Total discount amount applied to the cart.
   */
  discountTotal?: IMoney;

  /**
   * Total tax amount applied to the cart.
   */
  taxTotal?: IMoney;

  /**
   * Shipping fee total.
   */
  shippingTotal?: IMoney;

  /**
   * Grand total payable.
   */
  total: IMoney;

  /**
   * Discounts applied to the cart (if any).
   */
  discounts?: ReadonlyArray<ICartDiscount>;
}

/**
 * The cart entity shape commonly stored in state management.
 */
export interface ICart {
  /**
   * Cart identifier (session/cart id).
   */
  id: string;

  /**
   * Currency used by the cart.
   */
  currency: CurrencyCode;

  /**
   * Items in the cart.
   */
  items: ReadonlyArray<ICartItem>;

  /**
   * Summary totals for UI and checkout.
   */
  summary: ICartSummary;

  /**
   * Applied shipping selection (if any).
   */
  shipping?: ICartShipping;

  /**
   * Tax details (if any).
   */
  tax?: ICartTax;

  /**
   * Cart-level metadata for integrations/experiments.
   */
  metadata?: Readonly<Record<string, string>>;

  /**
   * Timestamp when cart was created.
   */
  createdAt?: ISODateTimeString;

  /**
   * Timestamp when cart was last updated.
   */
  updatedAt?: ISODateTimeString;
}

/**
 * Payload to add an item to the cart.
 */
export interface IAddToCartInput {
  productRef: IProductRef;
  quantity: number;
  /**
   * Optional attributes to disambiguate item selection (e.g. size/color).
   */
  attributes?: Readonly<Record<string, string>>;
  /**
   * Optional note for the line item.
   */
  note?: string;
}

/**
 * Payload to update an existing cart item.
 */
export interface IUpdateCartItemInput {
  id: CartItemId;
  quantity?: number;
  note?: string;
  attributes?: Readonly<Record<string, string>>;
}

/**
 * A minimal, stable representation to identify a line item by product/variant.
 * Useful for deduplication logic and selectors.
 */
export interface ICartItemKey {
  productId: ProductId;
  variantId?: VariantId;
  /**
   * Optional attributes participating in uniqueness rules.
   */
  attributes?: Readonly<Record<string, string>>;
}

/**
 * Common cart operation result.
 */
export interface ICartOperationResult {
  cart: ICart;
  /**
   * Optional warnings to surface to UI (e.g. "quantity adjusted due to stock").
   */
  warnings?: ReadonlyArray<string>;
}